### ISSUE TITLE
Is there an easy way to install it without Docker?

### ISSUE THREAD

**Issue by spidirs** [TrevorSatori/tempus#1]
Hi there,

Is there an easy method to install Tempus without Docker, please?

Thanks!

G.

**Comment by TrevorSatori** [comment]
What method would you prefer? Building from source is also an option.

**Comment by spidirs** [comment]
Hi Trevor,

Thanks for getting back to me, and you're absolutely right. I managed to install it on my Laragon following the steps outlined in the readme doc. It only required updating NodeJS to a newer version.

Please feel free to close this one.
